spring:
  application:
    name: test-serviceC
  datasource:
    url: jdbc:mysql://192.168.1.241:3306/test?serverTimezone=CTT&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: bec123456
    driver-class-name: com.mysql.cj.jdbc.Driver
#  zipkin:
#    base-url: http://localhost:9411
#  sleuth:
#    web:
#      client:
#        enabled: true
#    sampler:
#      probability: 1.0

server:
  port: 8002

mybatis:
  mapper-locations: classpath:mapper/*DaoC.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

tx-lcn:
  client:
    manager-address: localhost:8070

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/
    register-with-eureka: true
    fetch-registry: true
    enabled: true